---
  - name: "Add Oracle Jdk apt repo"
    sudo: yes
    sudo_user: root
    apt_repository: 
       repo='{{item}} http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' 
       state=present
    with_items:
      - deb
      - deb-src

  - name: "Select Oracle License"
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

  - name: "Install Oracle JDK6"
    sudo: yes 
    sudo_user: root
    apt: pkg=oracle-java{{jdk_version}}-installer state=present force=yes

